name: network_security

dependencies:
- python>=3.8.5
- backcall==0.2.0
- certifi==2020.11.8
- colorama==0.4.3
- cycler==0.10.0
- decorator==4.4.2
- ipykernel==5.3.4
- ipython==7.18.1
- jedi==0.17.2
- joblib==0.17.0
- kiwisolver==1.3.0
- matplotlib==3.3.2
- mkl-service==2.3.0
- numpy==1.19.2
- olefile==0.46
- pandas==1.1.3
- parso==0.7.0
- patsy==0.5.1
- pickleshare==0.7.5
- Pillow==8.0.1
- pip==20.3
- prompt-toolkit==3.0.8
- Pygments==2.7.1
- pyparsing==2.4.7
- python-dateutil==2.8.1
- pytz==2020.1
- pywin32==227
- pyzmq==19.0.2
- scipy==1.5.0
- seaborn==0.11.0
- sip==4.19.13
- six==1.15.0
- statsmodels==0.12.0
- threadpoolctl==2.1.0
- tornado==6.0.4
- traitlets==5.0.5
- wcwidth==0.2.5
- wheel==0.35.1
- wincertstore==0.2


- pip:
  - jupyter-client==6.1.7
  - loo-encoder==0.0.9
  - jupyter-core==4.6.3
  - setuptools==46.2.0
  - sklearn==0.0
  - ipython-genutils==0.2.0
  - scikit-learn==0.24.dev0
  - category-encoders==2.2.2


  